import os
import requests
from pathlib import Path
from datetime import datetime, timezone
from urllib.parse import quote
from typing import Optional, Dict, Any
from src.config import GITHUB_TOKEN, GITHUB_REPOSITORY

# Network timeouts (connect, read). The upload gets a long read timeout because a
# multi-hundred-MB asset legitimately takes minutes -- but not *forever*, so a
# stalled socket can't silently consume the whole 90-minute CI job.
_API_TIMEOUT = (10, 60)
_UPLOAD_TIMEOUT = (10, 600)


def _utc_now() -> datetime:
    return datetime.now(timezone.utc)

def upload_clip_to_github_release(
    clip_path: Path,
    tag_name: Optional[str] = None,
    repo: Optional[str] = None,
    token: Optional[str] = None
) -> Optional[str]:
    """
    Uploads an MP4 clip as a GitHub Release asset for $0 permanent public hosting.
    Returns direct public URL: https://github.com/{repo}/releases/download/{tag}/{filename}
    """
    auth_token = token or GITHUB_TOKEN
    target_repo = repo or GITHUB_REPOSITORY

    if not auth_token or not target_repo:
        print("[-] GITHUB_TOKEN or GITHUB_REPOSITORY not set. Cannot upload to GitHub Release.")
        print(f"[-] Video remains stored locally at: {clip_path}")
        return None

    headers = {
        "Authorization": f"Bearer {auth_token}",
        "Accept": "application/vnd.github.v3+json"
    }

    # Generate or reuse release tag
    tag = tag_name or f"clips-{_utc_now().strftime('%Y%m%d-%H%M%S')}"

    print(f"[*] Creating/Fetching GitHub Release '{tag}' in {target_repo}...")
    release_url = f"https://api.github.com/repos/{target_repo}/releases"

    try:
        # 1. Check if release already exists
        get_res = requests.get(f"{release_url}/tags/{tag}", headers=headers, timeout=_API_TIMEOUT)
        if get_res.status_code == 200:
            release_data = get_res.json()
        else:
            # Create new release
            create_payload = {
                "tag_name": tag,
                "target_commitish": "main",
                "name": f"Podcast Social Clips - {_utc_now().strftime('%Y-%m-%d')}",
                "body": "Automated viral podcast clips generated by AI Clipper Pipeline.",
                "draft": False,
                "prerelease": False
            }
            create_res = requests.post(release_url, headers=headers, json=create_payload, timeout=_API_TIMEOUT)
            if create_res.status_code not in (200, 201):
                print(f"[-] Failed to create GitHub release: {create_res.status_code} - {create_res.text}")
                return None
            release_data = create_res.json()
    except requests.RequestException as e:
        print(f"[-] GitHub release create/fetch failed: {e}")
        return None

    upload_url_template = release_data.get("upload_url")
    if not upload_url_template:
        print(f"[-] Unexpected GitHub release response (no upload_url): {release_data}")
        return None
    # URL format is: https://uploads.github.com/repos/{owner}/{repo}/releases/{id}/assets{?name,label}
    upload_base = upload_url_template.split("{")[0]

    filename = clip_path.name
    upload_headers = {
        "Authorization": f"Bearer {auth_token}",
        "Content-Type": "video/mp4"
    }

    print(f"[*] Uploading {filename} ({clip_path.stat().st_size / (1024*1024):.2f} MB) to GitHub Releases...")
    # Stream the file handle (do NOT read the whole multi-hundred-MB clip into RAM)
    # and URL-encode the name so titles with spaces/&/# produce a valid asset URL.
    try:
        with open(clip_path, "rb") as f:
            upload_res = requests.post(
                f"{upload_base}?name={quote(filename)}",
                headers=upload_headers,
                data=f,
                timeout=_UPLOAD_TIMEOUT,
            )
    except requests.RequestException as e:
        print(f"[-] Asset upload failed (network): {e}")
        return None

    if upload_res.status_code in (200, 201):
        asset_info = upload_res.json()
        direct_url = asset_info.get("browser_download_url")
        print(f"[+] Asset published! Permanent Direct URL: {direct_url}")
        return direct_url
    else:
        print(f"[-] Asset upload failed: {upload_res.status_code} - {upload_res.text}")
        return None
